spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=300MB
spring.servlet.multipart.file-size-threshold=1KB

server.port=${PORT:8080}
jwt.secret=${JWT_SECRET}

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.h2.console.enabled=false

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1











# #multipart configuration

# #enabling multipart uploads
# spring.servlet.multipart.enabled=true

# #max file size
# spring.servlet.multipart.max-file-size=300MB

# #threshold after which files are written to disk
# spring.servlet.multipart.file-size-threshold=1KB

# server.port=${PORT:8080}
# jwt.secret=${JWT_SECRET:defaultSecretKeyForJwtAuthenticationWhichIsVeryLongAndSecure}

# spring.jpa.hibernate.ddl-auto=update
# spring.datasource.url=${DB_URL:jdbc:mysql://908b7d.h.filess.io:3307/das_ui_ownermost?useSSL=false&serverTimezone=UTC}
# spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
# spring.datasource.username=${DB_USERNAME:das_ui_ownermost}
# spring.datasource.password=${DB_PASSWORD:3040b9dacfe2dec6e8646ca800cfe659a56091fd}
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# # Note: Since H2 console is not used for MySQL, we can remove or set it to false
# spring.h2.console.enabled=false
# #spring.jpa.show-sql: true

# # Fix for Filess.io max user connections limit
# spring.datasource.hikari.maximum-pool-size=2
# spring.datasource.hikari.minimum-idle=1